version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: onda
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nanna
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onda_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
